services:
  backend:
    build: 
      context: ./backend
    container_name: festudio_backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    restart: unless-stopped

  frontend:
    image: node:20-alpine
    container_name: festudio_frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "5174:5173"
    command: sh -c "npm install -g pnpm && pnpm install && pnpm run dev --host"
    env_file:
      - ./frontend/.env.local
    depends_on:
      - backend